<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Neatly.Uninstaller.Core\Neatly.Uninstaller.Core.csproj" />
    <ProjectReference Include="..\Neatly.Uninstaller.Win32\Neatly.Uninstaller.Win32.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
